services:
  mysql-for-musicsense:
    # image: mysql:8.0.33
    build: ./initdb
    container_name: mysql-for-musicsense
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "3307:3306"
      - "33061:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=musicsense
      # - MYSQL_DATABASE_HOST=0.0.0.0:3306
      - MYSQL_DATABASE_USERNAME=root
    networks:
      - musicsense-network
  
  musicsense-frontend:
    build: ./musicsense-frontend/
    container_name: musicsense-frontend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - musicsense-network

  musicsense-backend:
    build: ./MusicSense/ 
    container_name: musicsense-backend
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=musicsense
      - MYSQL_DATABASE_HOST=mysql-for-musicsense
      - MYSQL_DATABASE_USERNAME=root
    ports:
      - "8000:8000"
    networks:
      - musicsense-network   
networks:
  musicsense-network: